### PR TITLE
Update metrics name to align with schema.lua

### PR DESCRIPTION
**Pull request by jayhding**
Seems the actual metrics names used in schema.lua are not aligned with README.md

### CODE REVIEW

**Comment by jayhding** [comment]
Sorry @yciabaud, I should use another branch for my second commit. 

This pull request wasfortwas supposed to be only for thr readme doc. 

Anyhow, the second commit was not duplicating metrics. I didn't see a way to add two gauge metrica simply by change plugin configuration because value assignment is hard coded in `logger.lua`

**Comment by jayhding** [comment]
I'm new to lua so perhaps I understood wrongly. I did try to change plugin configuration from kong admin at first but did not work, maybe I missed something else.

**Comment by yciabaud** [comment]
The changes I can see in the documentation are reflecting the new metrics you've added.
The plugin should be configurable to add different metric type using the same value.

Can you try first to set this up and if you have trouble we could discuss it in an issue?
In this way we will know if this change is required or not.

**Comment by jayhding** [comment]
The first commit https://github.com/yciabaud/kong-plugin-prometheus/pull/8/commits/e5d6feb5433b3229e79f9ecd88e186d4c8c7971d is not related to the new metrics I added.

And for adding new metrics via plugin configuration do you mean I can have both below metrics?
```
{"name":"http_upstream_duration_ms","labels":["api"],"stat_type":"histogram"}
{"name":"http_upstream_duration_ms","labels":["api"],"stat_type":"gauge"}
```
Let me try that...

**Comment by yciabaud** [comment]
I can see the necessity of having the same measure used in different ways, I just think that we should be able to configure it without duplicating the metrics in the code.

Let me think about it a little bit.

**Comment by jayhding** [comment]
No need for this due to merged #10

**Comment by yciabaud** [comment]
Now #10 is merged can you remove the second commit from this PR and rebase it on master to update the documentation only?

**Comment by yciabaud** [comment]
Oh did not see you have closed this, I will update the documentation myself and release a version of this project.

**Comment by jayhding** [comment]
Oh right... just thought your changes are enough :)
Thanks for your effort anyway, good plugin 👍

**Pull request closed without merging**
